import { Metadata } from "next";
import { PopoverProvider } from "./_contexts/popover/popover";

export const metadata: Metadata = {
  title: "Planner",
  description: "Generated by create next app",
  icons: {
    icon: "/vite.svg",
  },
};

async function PlannerRootLayout({
  children,
  attendance,
}: {
  children: React.ReactNode;
  attendance: React.ReactNode | undefined;
}) {
  return (
    <PopoverProvider>
      {attendance}
      {children}
    </PopoverProvider>
  );
}

export default PlannerRootLayout;
