import { Metadata } from "next";
import LeaveRequestHeader from "./_components/header";
import RelationLeaveRequestClient from "./client";

export const metadata: Metadata = {
  title: "Leave request",
  description: "Generated by create next app",
  icons: {
    icon: "/vite.svg",
  },
};

async function RelationsRequestLeaves({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  return (
    <div className="w-full h-full">
      <LeaveRequestHeader searchParams={searchParams} />
      <RelationLeaveRequestClient />
    </div>
  );
}

export default RelationsRequestLeaves;
