import { Metadata } from "next";
import { ReactNode } from "react";
import RelationWarningHeader from "../_components/header";

export const metadata: Metadata = {
  title: "Warnings",
  description: "Generated by create next app",
  icons: {
    icon: "/vite.svg",
  },
};

async function RootRequestLayout({ children }: { children: ReactNode }) {
  return (
    <div className="h-screen w-full overflow-y-auto p-8">
      <div className="w-full max-w-[1262px] mx-auto cart-bg rounded-lg shadow-m min-h-full">
        <RelationWarningHeader />
        {children}
      </div>
    </div>
  );
}

export default RootRequestLayout;
