import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Employee Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "/vite.svg",
  },
};

async function RootRequestLayout({
  children,
  create,
}: {
  children: ReactNode;
  create: ReactNode | undefined;
}) {
  return (
    <>
      {create}
      {children}
    </>
  );
}

export default RootRequestLayout;
