import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Warning Detail",
  description: "Generated by create next app",
  icons: {
    icon: "/vite.svg",
  },
};

export default function RootLayout({
  children,
  detail,
}: Readonly<{
  children: React.ReactNode;
  detail: React.ReactNode | undefined;
}>) {
  return (
    <>
      {detail}
      {children}
    </>
  );
}
