import { Metadata } from "next";
import RelationsWarningsPublishedClient from "./client";

export const metadata: Metadata = {
  title: "Warnings",
  description: "Generated by create next app",
  icons: {
    icon: "/vite.svg",
  },
};

async function RelationsWarningsPublished({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  return <RelationsWarningsPublishedClient />;
}

export default RelationsWarningsPublished;
