import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Organization",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="flex w-full h-screen">{children}</div>;
}
