import { getCompany } from "@/data/user";
import EmployeeModel from "@/models/employees/model";
import dayjs from "dayjs";
import { CalendarDays } from "lucide-react";
import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import PlannerAttendanceDetailHeader from "./header";
import ResignationPrintBtn from "./printbtn";

export const metadata: Metadata = {
  title: "Generate Attendance",
  description: "Generated by create next app",
  icons: {
    icon: "/vite.svg",
  },
};

async function PlannerAttendanceDetailLayout({
  params,
  children,
}: {
  params: { id: string };
  children: React.ReactNode;
}) {
  const { id } = params;
  const company = await getCompany();
  const employee = await EmployeeModel.findById(id)
    .select("profile.image name nickname employeeId joinedDate")
    .populate("position department", "name");

  if (!employee) return notFound();

  const src = employee.profile?.image
    ? `/api/images/${employee.profile.image}/300/300`
    : "";

  return (
    <div className="w-full h-screen overflow-y-auto px-8 pt-8 pb-4">
      <div className="cart-bg rounded-lg shadow-m min-h-full max-w-[1000px] mx-auto">
        <PlannerAttendanceDetailHeader />
        <div className="p-2 flex border-b">
          <Image
            width={200}
            height={320}
            className="rounded-lg min-h-[200px] max-h-[200px]"
            src={src}
            alt="profile"
          />
          <div className="px-4 h-[200px]">
            <p className="font-bold text-lg">
              {employee.name}{" "}
              <span className="inactive-text text-sm">
                ({employee.employeeId})
              </span>
            </p>
            <p>{employee.position?.name}</p>
            <p>{employee.department?.name}</p>
            <p className="flex items-center">
              <CalendarDays className="mr-2 h-4 w-4 opacity-70" /> Joined{" "}
              {dayjs(employee.joinedDate).format("MMMM YYYY")}
            </p>
            <div className="mt-4">
              <ResignationPrintBtn
                data={JSON.stringify(employee)}
                company={JSON.stringify(company)}
              />
            </div>
          </div>
        </div>
        {children}
      </div>
    </div>
  );
}

export default PlannerAttendanceDetailLayout;
